UnknownServiceError: Unknown service: 'bedrock-agentcore-control' has been occurring due to older version of packages, hence explicit upgrade commands are added to notebook.
%pip install --upgrade boto3
%pip install --upgrade bedrock-agentcore
%pip install --upgrade bedrock_agentcore_starter_toolkit